### ISSUE TITLE
Plug custom generators

### ISSUE THREAD

**Issue by arichiardi** [plumatic/schema-generators#4]
Hello there! Nice and useful tool :+1:

Is there a way to extend the generator with custom ones for a particular leaf?

Example:

```
(def Workflow {:id PosInt
               :scan-left (s/maybe ScanJson)
               :scan-right (s/maybe ScanJson)
               :status WorkflowStatus
               :user-id (lt NonEmptyStr 40)
               :last-modified s/Inst})
```

I would like to be able to generate a Json, therefore wrap data generated for a `Scan` with `cheshire` so that I just need:

`(generate cs/Workflow)`

instead of:

```
(-> (generate cs/Workflow)
    (assoc :scan-left (json (generate cs/Scan)))
    (assoc :scan-right (json (generate cs/Scan)))
    ...
```

**Comment by w01fe** [comment]
Thanks!  

Sure, you just pass the leaf generators as an argument.  e.g.

`(generate cs/Workflow {(s/maybe ScanJson) (json (generate cs/Scan))})`.  Is that what you're looking for? 

Also, in the future can you please ask questions on the mailing list rather than as github issues?  Thanks!

**Comment by arichiardi** [comment]
Thank you! I will try the solution, and I apoligize for writing here...

**Comment by w01fe** [comment]
No worries, please let me know if you run into any problems or other
issues.

**Comment by arichiardi** [comment]
I get a weird: `java.lang.AssertionError: Assert failed: Second arg to fmap must be a generator (generator? gen)`, it must come from `test-check`...digging...

**Comment by w01fe** [comment]
Oops, in my message `(json (generate cs/Scan))` should actually be a generator.  so actually something like `(fmap json (generator cs/Scan))` instead.

**Comment by arichiardi** [comment]
Yes I then digged a bit more and discovered above fmap and return (which I am using in some other case) :wink:
