### ISSUE TITLE
Generate s/Int produces clojure.lang.BigInt

### ISSUE THREAD

**Issue by arichiardi** [plumatic/schema-generators#6]
Hello again :smile:, I was trying this with test-check and got into a `clojure.lang.BigInt` instance.

I don't know if this is expected behavior but I thought of reporting it:

```
dev> (generate s/Int)
234
dev> (generate s/Int)
429
dev> (generate s/Int)
2
dev> (generate s/Int)
51N
```

Thanks as usual for checking this.

**Comment by w01fe** [comment]
I think so, s/Int represents any kind of Clojure integral type.

If you want a specific type, you can use Integer or Long (or the primitive
int/long).  Is that what you're looking for?

**Comment by arichiardi** [comment]
Yes I ended up using the specific Java type so no issue, but if it is expected, I am going to close this :smile:
